# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
