# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20170330_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('random', models.CharField(max_length=500)),
            ],
        ),
    ]
