# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_auto_20170419_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=500),
        ),
    ]
