# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0013_userrecommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpass',
            name='username',
        ),
        migrations.AddField(
            model_name='forgotpass',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
