# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_auto_20170422_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpass',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
