# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0017_auto_20170422_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpass',
            name='user',
        ),
        migrations.AddField(
            model_name='forgotpass',
            name='username',
            field=models.CharField(default='', max_length=500),
        ),
    ]
