# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0018_auto_20170422_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpass',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
